UC_TARGET = "atmega328p"
PROGRAMMER = "usbtiny"

desc "Compiles firmware"
task :build => [:clean] do
  puts `avr-gcc -std=c99 -O2 -Os -mmcu=#{UC_TARGET} -o main.elf main.c && avr-objcopy -R .eeprom -O ihex main.elf firmware.hex`
end


desc "Load firmware onto uC"
task :install do
  if File.exists? 'firmware.hex'
    puts `avrdude -p #{UC_TARGET} -c #{PROGRAMMER} -v -U flash:w:firmware.hex`
  else
    puts "Cannot upload firmware, firmware.hex not present. Did you forget to run build? A compiler error perhaps?"
  end
end

task :clean do
  ['main.elf', 'firmware.hex'].each { |file| File.delete(file) if File.exists?(file) }
end

task :all => [:build, :install]
task :default => [:all]